trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build the Docker image
  jobs:
  - job: Build
    displayName: Build job
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: $(Build.SourcesDirectory)/Dockerfile

- stage: Run
  displayName: Run the container
  jobs:
  - job: Run
    displayName: Run job
    steps:
    - task: Docker@2
      displayName: Run container
      inputs:
        command: run
        dockerfile: $(Build.SourcesDirectory)/Dockerfile
        ports: 8000
