trigger:
- develop

pool:
  name: Default
  #name: MySelfHostedAgentPool  # Replace with your self-hosted agent pool name

stages:
- stage: Build
  displayName: Build and run the Docker image
  jobs:
  - job: Build
    displayName: Build and run job
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: $(Build.SourcesDirectory)/Dockerfile
    - task: CmdLine@2
      displayName: Tag Docker image
      inputs:
        script: |
          docker tag $(docker_image_name) $(docker_image_name):$(Build.BuildId)
    - task: CmdLine@2
      displayName: Run Docker container
      inputs:
        script: |
          docker run $(docker_image_name):$(Build.BuildId)
